import { type NextPage } from "next";
import Head from "next/head";
import Profile from "~/components/profile/Profile";
import Skills from "~/components/skills/Skills";
import Timeline from "~/components/timeline/Timeline";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fachkarriere Tool</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="mx-8 my-4">
        <h1 className="text-3xl">Marc Aumüller</h1>
      </header>
      <main className="mx-8 grid grid-cols-3">
        <div className="col-span-2">
          <Timeline />
        </div>
        <div className="col-span-1">
          <Profile />
        </div>
      </main>
      <footer className="absolute bottom-0 mx-8 my-4">
          <Skills />
      </footer>
    </>
  );
};

export default Home;
